TimeChimp/tacugama

- src/components/portal/index.ts
This reverts commit 37691bdf559120dc7d0a663954036f2912f83215.
Closes #30
> Revert "Add ssr support to portal"

- src/components/textarea/Textarea.tsx
- src/components/textarea/index.tsx
- src/models/constants.ts
- src/models/index.ts
> Update textarea component

- .gitignore
- package.json
- src/components/confirmation-modal/ConfirmationModal.stories.tsx
> Increase size limit

- .github/workflows/release.yml
- README.md
- package-lock.json
- package.json
> Add auto publish workflow

- .storybook/preview-head.html
> feat: add source sans pro

- .storybook/preview-head.html
- package.json
- src/theme/primitives.ts
Reverts TimeChimp/tacugama#377
> Revert "feat: implement inter font"

- .github/workflows/main.yml
> test: remove macos from main action

- src/components/copy-text/CopyText.tsx
> fix: remove copy text circular dependency

- package-lock.json
- src/components/data-grid/types.ts
- src/components/row-select/RowSelect.tsx
> fix: resolve warnings

- package.json
- src/components/input/hours-input/types.ts
We had to fight jaguars just to be able to commit this code :tiger:
> fix: add missing props in the jungle

- package.json
- src/components/data-grid/row-actions-cell/RowActionsCell.tsx
fixed submit for row actions cell
> fix(CSR-3071): customer portals

- package.json
- src/components/button/Button.stories.tsx
- src/components/button/Button.tsx
- src/components/button/index.ts
- src/components/button/modal-button/ModalButton.tsx
- src/components/button/secondary-button/SecondaryButton.tsx
- src/components/button/secondary-modal-button/SecondaryModalButton.tsx
- src/components/button/square-button/SquareButton.tsx
- src/components/button/square-button/index.ts
- src/components/checkbox/Checkbox.stories.tsx
- src/components/checkbox/Checkbox.tsx
- src/theme/colors.ts
- Added `SquareButton` component
- Updated `CheckBox` styling to match designs
> fix: styling updates

- package.json
- src/components/checkbox/Checkbox.tsx
- src/components/data-grid/DataGrid.stories.tsx
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/__tests__/constants.tsx
- src/components/data-grid/filters/Filters.tsx
- src/components/data-grid/header-checkbox/HeaderCheckbox.tsx
- src/components/data-grid/styles.ts
- src/components/data-grid/views/create-view-modal/CreateViewModal.tsx
- src/components/data-grid/views/data-grid-view-options/DataGridViewOptions.tsx
- src/components/data-grid/views/rename-view-modal/RenameViewModal.tsx
- src/components/dropdown/Dropdown.tsx
- src/components/input/Input.stories.tsx
- src/components/input/search-input/SearchInput.tsx
- src/components/input/search-input/index.ts
- src/components/input/search-input/types.ts
- Search input styling
- Revert Checkbox component styling
- Data grid view modals
> fix: various styling issues

- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/styles.ts
- src/components/data-grid/types.ts
[Link to CSR-3229](https://timechimp.atlassian.net/browse/CSR-3229)
> feat(CSR-3229): Fix data grid errors

- package.json
- src/components/data-grid/DataGrid.stories.tsx
- src/components/data-grid/types.ts
[Link to CSR-3745](https://timechimp.atlassian.net/browse/CSR-3745)
> feat(CSR-3745): Fix custom component type

- package-lock.json
- package.json
- src/components/drawer/Drawer.stories.tsx
- src/components/drawer/index.ts
Make drawer component available with default settings. Probably will have a redesign later on.
> add drawer element

- package.json
- src/components/select/Select.tsx
> temp fix select

- package.json
- src/components/data-grid/DataGrid.tsx
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?modal=detail&selectedIssue=CSR-3846&assignee=63ff4d19314f50881381751a)
Changed:
if (isSearchColumn) {
return 'agTextColumnFilter';
}
to
if (isSearchColumn) {
return 'agMultiColumnFilter';
}
The rest is linting
> data grid combine search with filters

- package.json
- src/models/Theme.ts
- src/theme/sizing.ts
[Link to CSR-3795](https://timechimp.atlassian.net/browse/CSR-3795)
> [CSR-3795] Add custom size

- package.json
- src/components/avatar/Avatar.tsx
- src/components/avatar/styles.ts
- src/components/dot/Dot.tsx
- src/components/radio/radio-item/RadioItem.tsx
- src/components/toggle/Toggle.tsx
- Toggle component disabled state
- Avatar component mixing short and long hand properties
> fix: style errors

- package.json
- src/components/toggle/Toggle.stories.tsx
- src/components/toggle/Toggle.tsx
[Link to CSR-3840](https://timechimp.atlassian.net/browse/CSR-3840)
> [CSR-3840] Toggle disabled style

- src/components/data-grid/DataGrid.stories.tsx
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/__tests__/constants.tsx
- src/components/data-grid/header-checkbox/HeaderCheckbox.tsx
- src/components/data-grid/styles.ts
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?modal=detail&selectedIssue=CSR-3958&assignee=63ff4d19314f50881381751a)
> Minor datagrid changes

- package-lock.json
- package.json
- src/components/input/Input.tsx
- src/components/input/number-input/NumberInput.tsx
- src/components/input/number-input/types.ts
- src/components/input/types.ts
- src/components/textarea/Textarea.tsx
- src/components/textarea/types.ts
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?modal=detail&selectedIssue=CSR-3877&assignee=63ff4d19314f50881381751a)
Needed for loading states
> add skeleton to inputs

- package-lock.json
- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/types.ts
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?modal=detail&selectedIssue=CSR-3958&assignee=63ff4d19314f50881381751a)
> datagrid minor changes

- package-lock.json
- package.json
- src/components/basic-table/BasicTable.tsx
- src/components/movable-table/MovableTable.stories.tsx
- src/components/movable-table/MovableTable.tsx
- src/components/movable-table/index.ts
- src/models/constants.ts
[Link to CSR-4008](https://timechimp.atlassian.net/browse/CSR-4008)
> [CSR-4008] Implement drag and drop table

- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/defaultTranslations.tsx
- src/components/data-grid/filters/ColumnFilters.tsx
- src/components/data-grid/types.ts
- src/components/movable-table/MovableTable.stories.tsx
[Link to CSR-4083](https://timechimp.atlassian.net/browse/CSR-4083)
> [CSR-4083] Add clear filters button

- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/filters/ColumnFilters.tsx
- src/components/data-grid/types.ts
[Link to CSR-4074](https://timechimp.atlassian.net/browse/CSR-4074)
> [CSR-4074] Add table settings filtering

- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/filters/ColumnFilters.tsx
- src/components/data-grid/types.ts
Makes it possible to pass multiple defaultvalues
Make it possible to set 'showLessFilters' from outside of the component
> [CSR-4283] support defaultvalues as array and set showLessfilters

- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/filters/Filters.tsx
- src/components/data-grid/types.ts
[Link to CSR-4185](https://timechimp.atlassian.net/browse/CSR-4185)
> [CSR-4185] Set filters height

- package-lock.json
- package.json
- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/footer-pagination/FooterPagination.tsx
disable filterviews for now 
add future support for changing the page from outside of tacugama
> [CSR-4300] Disable view filtermodel

- package-lock.json
- package.json
- src/components/data-grid/filters/ColumnFilters.tsx
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?modal=detail&selectedIssue=CSR-4537&assignee=63ff4d19314f50881381751a)
> [CSR-4537] Hide show more button if filter is hidden

- package.json
- src/components/file-upload/FileUpload.tsx
Fixed behavior when we press the Enter Key in an input form, and then the file selector automatically opened
> [CSR-4658] Fixed file-upload form component behavior

- package-lock.json
- package.json
- src/components/basic-table/BasicTable.stories.tsx
- src/components/basic-table/BasicTable.tsx
- src/components/basic-table/Cell.tsx
- src/components/basic-table/EmptyMessage.tsx
- src/components/basic-table/__tests__/constants.tsx
- src/components/basic-table/types.ts
- src/components/button/Button.stories.tsx
- src/components/button/Button.tsx
- src/components/button/types.ts
- src/models/ButtonShape.ts
- src/models/constants.ts
- src/models/index.ts
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?modal=detail&selectedIssue=CSR-4704&assignee=63ff4d19314f50881381751a)
> [CSR-4704] Basictable change empty state

- package-lock.json
- package.json
- src/components/basic-table/BasicTable.tsx
Fix alignment empty table text when used in next
> [CSR-0000] Fix alignment empty table

- package-lock.json
- package.json
- src/components/input/Input.stories.tsx
- src/components/input/Input.tsx
- src/components/input/hours-input/HoursInput.tsx
- src/components/input/number-input/NumberInput.tsx
- src/components/input/number-input/types.ts
- src/components/input/price-input/types.ts
- src/components/input/types.ts
- src/models/PriceInputPrefixes.ts
- Specifically `Number`, `Price` and `Hours` input
> Update input styling

- package.json
- src/components/dropdown/dropdown-option/DropdownOption.tsx
[Link to CSR-4776](https://timechimp.atlassian.net/browse/CSR-4776)
> [CSR-4776] Fix tooltip size

- package-lock.json
- package.json
- src/components/basic-table/BasicTable.tsx
- src/components/movable-table/MovableTable.tsx
fix console errors and remove unused styling
> [CSR-0000] Fix console errors

- package-lock.json
- package.json
- src/components/edit-page/EditPage.tsx
- src/components/edit-page/EditPageContent.tsx
- src/components/edit-page/index.ts
- src/components/edit-page/types.ts
Separate content wrapper in edit page so this can be used separate from the header
> [CSR-4453] Separate edit content wrapper

- package.json
- src/components/edit-page/EditPageSkeleton.tsx
[Link to CSR-4872](https://timechimp.atlassian.net/browse/CSR-4872)
> [CSR-4872] Fix sleketon gap

- package.json
- src/components/datepicker/Datepicker.tsx
[Link](https://timechimp.atlassian.net/jira/software/c/projects/CSR/boards/19?assignee=63ff4d19314f50881381751a&selectedIssue=CSR-4951)
> [CSR-4951] Fix height datepicker

- src/components/data-grid/DataGrid.tsx
- src/components/data-grid/__tests__/constants.tsx
- src/components/data-grid/types.ts
[Link to CSR-5058](https://timechimp.atlassian.net/browse/CSR-5058)
> [CSR-5058] Add data grid extra filter

- package-lock.json
- package.json
- src/components/data-grid/DataGrid.tsx
Disable regular columns to be pinned by dragging. 
Lock position of right pinned column.
> [CSR-0000] Lock pinned datagrid

- package-lock.json
- package.json
- src/components/data-grid/filters/ColumnFilters.tsx
- src/components/datepicker/index.ts
- src/components/select/multi-select/MultiSelect.tsx
- src/components/select/single-select/SingleSelect.tsx
Revert datepicker at datagrid to what it was before
> Revert datepicker datagrid

- package-lock.json
- package.json
- src/components/date-filter/DateFilter.stories.tsx
- src/components/datepicker/components/calendar/CalendarComponent.tsx
- src/components/datepicker/components/calendar/types.ts
- src/components/dropdown/styles.ts
Add theme color to datepicker
Also added custom hover states
> [CSR-0000] Change color datepicker

- package-lock.json
- package.json
- src/components/data-grid/filters/ColumnFilters.tsx
- src/components/date-filter/DateFilter.tsx
- src/models/QuickSelectDateOption.ts
Add all period filter to ag grid
> [CSR-0000] Add all period filter
